# @generated by `cargo buckal`

load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "buildscript_run", "rust_binary", "rust_library", "rust_test")

filegroup(
    name = "fd-find-vendor",
    srcs = glob(["**/**"]),
    out = "vendor",
)

cargo_manifest(
    name = "fd-find-manifest",
    vendor = ":fd-find-vendor",
)

rust_binary(
    name = "fd",
    srcs = [":fd-find-vendor"],
    crate = "fd",
    crate_root = "vendor/src\\main.rs",
    edition = "2021",
    env = {
        "OUT_DIR": "$(location :fd-find-build-script-run[out_dir])",
    },
    features = [
        "clap_complete",
        "completions",
        "default",
        "tikv-jemallocator",
        "use-jemalloc",
    ],
    rustc_flags = [
        "@$(location :fd-find-build-script-run[rustc_flags])",
        "@$(location :fd-find-manifest[env_flags])",
    ] + select({
        "prelude//os/constraints:windows": select({
            "prelude//abi/constraints:gnu": [
                "@$(location //third-party/rust/crates/windows_x86_64_gnu/0.52.6:windows_x86_64_gnu-build-script-run[rustc_flags])",
                "@$(location //third-party/rust/crates/windows_x86_64_gnu/0.53.0:windows_x86_64_gnu-build-script-run[rustc_flags])",
                "@$(location //third-party/rust/crates/winapi-x86_64-pc-windows-gnu/0.4.0:winapi-x86_64-pc-windows-gnu-build-script-run[rustc_flags])",
            ],
            "prelude//abi/constraints:msvc": select({
                "prelude//cpu/constraints:arm64": [
                    "@$(location //third-party/rust/crates/windows_aarch64_msvc/0.52.6:windows_aarch64_msvc-build-script-run[rustc_flags])",
                    "@$(location //third-party/rust/crates/windows_aarch64_msvc/0.53.0:windows_aarch64_msvc-build-script-run[rustc_flags])",
                ],
                "prelude//cpu/constraints:x86_32": [
                    "@$(location //third-party/rust/crates/windows_i686_msvc/0.52.6:windows_i686_msvc-build-script-run[rustc_flags])",
                    "@$(location //third-party/rust/crates/windows_i686_msvc/0.53.0:windows_i686_msvc-build-script-run[rustc_flags])",
                ],
                "DEFAULT": [
                    "@$(location //third-party/rust/crates/windows_x86_64_msvc/0.52.6:windows_x86_64_msvc-build-script-run[rustc_flags])",
                    "@$(location //third-party/rust/crates/windows_x86_64_msvc/0.53.0:windows_x86_64_msvc-build-script-run[rustc_flags])",
                ],
            }),
            "DEFAULT": select({
                "prelude//cpu/constraints:arm64": [
                    "@$(location //third-party/rust/crates/windows_aarch64_msvc/0.52.6:windows_aarch64_msvc-build-script-run[rustc_flags])",
                    "@$(location //third-party/rust/crates/windows_aarch64_msvc/0.53.0:windows_aarch64_msvc-build-script-run[rustc_flags])",
                ],
                "prelude//cpu/constraints:x86_32": [
                    "@$(location //third-party/rust/crates/windows_i686_msvc/0.52.6:windows_i686_msvc-build-script-run[rustc_flags])",
                    "@$(location //third-party/rust/crates/windows_i686_msvc/0.53.0:windows_i686_msvc-build-script-run[rustc_flags])",
                ],
                "DEFAULT": [
                    "@$(location //third-party/rust/crates/windows_x86_64_msvc/0.52.6:windows_x86_64_msvc-build-script-run[rustc_flags])",
                    "@$(location //third-party/rust/crates/windows_x86_64_msvc/0.53.0:windows_x86_64_msvc-build-script-run[rustc_flags])",
                ],
            }),
        }),
        "DEFAULT": [],
    }),
    os_deps = {
        "linux": [
            "//third-party/rust/crates/libc/0.2.174:libc",
            "//third-party/rust/crates/nix/0.30.1:nix",
            "//third-party/rust/crates/tikv-jemallocator/0.6.0:tikv-jemallocator",
        ],
        "macos": [
            "//third-party/rust/crates/libc/0.2.174:libc",
            "//third-party/rust/crates/nix/0.30.1:nix",
        ],
    },
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aho-corasick/1.1.3:aho-corasick",
        "//third-party/rust/crates/anyhow/1.0.98:anyhow",
        "//third-party/rust/crates/argmax/0.4.0:argmax",
        "//third-party/rust/crates/clap/4.5.42:clap",
        "//third-party/rust/crates/clap_complete/4.5.55:clap_complete",
        "//third-party/rust/crates/crossbeam-channel/0.5.15:crossbeam-channel",
        "//third-party/rust/crates/ctrlc/3.4.7:ctrlc",
        "//third-party/rust/crates/etcetera/0.10.0:etcetera",
        "//third-party/rust/crates/faccess/0.2.4:faccess",
        "//third-party/rust/crates/globset/0.4.16:globset",
        "//third-party/rust/crates/home/0.5.9:home",
        "//third-party/rust/crates/ignore/0.4.23:ignore",
        "//third-party/rust/crates/jiff/0.2.15:jiff",
        "//third-party/rust/crates/lscolors/0.20.0:lscolors",
        "//third-party/rust/crates/normpath/1.3.0:normpath",
        "//third-party/rust/crates/nu-ansi-term/0.50.1:nu-ansi-term",
        "//third-party/rust/crates/regex-syntax/0.8.5:regex-syntax",
        "//third-party/rust/crates/regex/1.11.1:regex",
    ],
)

rust_binary(
    name = "fd-find-build-script-build",
    srcs = [":fd-find-vendor"],
    crate = "build_script_build",
    crate_root = "vendor/build.rs",
    edition = "2021",
    features = [
        "clap_complete",
        "completions",
        "default",
        "tikv-jemallocator",
        "use-jemalloc",
    ],
    rustc_flags = ["@$(location :fd-find-manifest[env_flags])"],
    visibility = [],
    deps = ["//third-party/rust/crates/version_check/0.9.5:version_check"],
)

buildscript_run(
    name = "fd-find-build-script-run",
    package_name = "fd-find",
    buildscript_rule = ":fd-find-build-script-build",
    env_srcs = [":fd-find-manifest[env_dict]"],
    features = [
        "clap_complete",
        "completions",
        "default",
        "tikv-jemallocator",
        "use-jemalloc",
    ],
    version = "10.3.0",
    manifest_dir = ":fd-find-vendor",
    visibility = ["PUBLIC"],
)
