# @generated by `cargo buckal`

load("@prelude//rust:cargo_package.bzl", "cargo")
load("@buckal//:cargo_buildscript.bzl", __buildscript_run__="buildscript_run")

def _set_profile_flag(**kwargs):
    rustc_flags = kwargs.get("rustc_flags", []) + select({
        "buckal//config/mode:debug": ["-Copt-level=0"],
        "buckal//config/mode:release": ["-Copt-level=3"],
        "DEFAULT": [],
    })
    return rustc_flags

def _patch_buildscript_env(**kwargs):
    env = kwargs.get("env", {})
    env.update(OPT_LEVEL=select({
        "buckal//config/mode:debug": "0",
        "buckal//config/mode:release": "3",
        "DEFAULT": "0",
    }))
    env.update(DEBUG=select({
        "buckal//config/mode:debug": "1",
        "buckal//config/mode:release": "0",
        "DEFAULT": "1",
    }))
    return env

def rust_binary(name, **kwargs):
    deps = kwargs.pop("deps", [])
    os_deps = kwargs.pop("os_deps", {})
    named_deps = kwargs.pop("named_deps", {})
    os_named_deps = kwargs.pop("os_named_deps", {})
    deps = _merge_os_deps(deps, os_deps)
    named_deps = _merge_os_named_deps(named_deps, os_named_deps)
    kwargs.update(deps = deps, named_deps = named_deps)
    # Set the crate name in the environment
    crate_name = kwargs.get("crate")
    env = kwargs.get("env", {})
    env.update(CARGO_CRATE_NAME=crate_name)
    kwargs.update(env=env)
    # Set build profile flags
    rustc_flags = _set_profile_flag(**kwargs)
    kwargs.update(rustc_flags=rustc_flags)
    cargo.rust_binary(name = name, **kwargs)

def rust_library(name, **kwargs):
    deps = kwargs.pop("deps", [])
    os_deps = kwargs.pop("os_deps", {})
    named_deps = kwargs.pop("named_deps", {})
    os_named_deps = kwargs.pop("os_named_deps", {})
    deps = _merge_os_deps(deps, os_deps)
    named_deps = _merge_os_named_deps(named_deps, os_named_deps)
    kwargs.update(deps = deps, named_deps = named_deps)
    # Set the crate name in the environment
    crate_name = kwargs.get("crate")
    env = kwargs.get("env", {})
    env.update(CARGO_CRATE_NAME=crate_name)
    kwargs.update(env=env)
    # Set build profile flags
    rustc_flags = _set_profile_flag(**kwargs)
    kwargs.update(rustc_flags=rustc_flags)
    cargo.rust_library(name = name, **kwargs)

def rust_test(name, **kwargs):
    deps = kwargs.pop("deps", [])
    os_deps = kwargs.pop("os_deps", {})
    named_deps = kwargs.pop("named_deps", {})
    os_named_deps = kwargs.pop("os_named_deps", {})
    deps = _merge_os_deps(deps, os_deps)
    named_deps = _merge_os_named_deps(named_deps, os_named_deps)
    kwargs.update(deps = deps, named_deps = named_deps)
    # Set the crate name in the environment
    crate_name = kwargs.get("crate")
    env = kwargs.get("env", {})
    env.update(CARGO_CRATE_NAME=crate_name)
    kwargs.update(env=env)
    # Set build profile flags
    rustc_flags = _set_profile_flag(**kwargs)
    kwargs.update(rustc_flags=rustc_flags)
    cargo.rust_test(name = name, **kwargs)

def buildscript_run(name, **kwargs):
    # Patch build script environment
    env = kwargs.get("env", {})
    env = _patch_buildscript_env(env=env)
    kwargs.update(env=env)
    __buildscript_run__(name = name, **kwargs)

def _merge_os_deps(default_deps, os_deps):
    if not os_deps:
        return default_deps
    base = list(default_deps)
    select_map = {"DEFAULT": base}
    for os_key, extras in os_deps.items():
        select_map[_platform_label(os_key)] = base + list(extras)
    return select(select_map)

def _merge_os_named_deps(default_named, os_named_deps):
    if not os_named_deps:
        return default_named
    base = dict(default_named)
    os_keys = set()
    for per_os in os_named_deps.values():
        os_keys.update(per_os.keys())

    def named_for(os_key):
        merged = dict(base)
        for alias, per_os in os_named_deps.items():
            if os_key in per_os:
                merged[alias] = per_os[os_key]
        return merged

    select_map = {"DEFAULT": base}
    for os_key in os_keys:
        select_map[_platform_label(os_key)] = named_for(os_key)

    return select(select_map)

def _platform_label(os_key):
    mapping = {
        "linux": "prelude//os:linux",
        "macos": "prelude//os:macos",
        "windows": "prelude//os:windows",
    }
    return mapping.get(os_key, os_key)
